### ISSUE TITLE
Request: NekoMod of HIFIMAN Sundara (Dekoni heepskin Earpads) from jaakkopasanen

### ISSUE THREAD

**Issue by githubbapoopa** [NekoAlosama/AutoEq-optimized#24]
Hope it's ok to ask for your mod here as I don't know how to reach out to you otherwise.

I'd like to have a NekoMod of HIFIMAN Sundara (Dekoni heepskin Earpads) from jaakkopasanen.

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/HIFIMAN%20Sundara%20(Dekoni%20heepskin%20Earpads)

Thanks!

**Comment by NekoAlosama** [comment]
I'll get to that soon, give me a few days.

**Comment by NekoAlosama** [comment]
First, I'm going to implement a fix for the [Problem causing / Error causing headphones](https://github.com/NekoAlosama/AutoEQ-NekoMod#problems-caused), then I'll make the results for all the headphones so that yours is in my repo so I can just link it to ya.

**Comment by githubbapoopa** [comment]
Alright. Thanks for looking into that. Much appreciated.
Take your time.

**Comment by NekoAlosama** [comment]
Here ya go
https://github.com/NekoAlosama/AutoEQ-NekoMod/tree/main/results/oratory1990/harman_over-ear_2018/HIFIMAN%20Sundara%20(Dekoni%20heepskin%20Earpads)

**Comment by githubbapoopa** [comment]
That was quick! Thanks so much!!!

**Comment by NekoAlosama** [comment]
Closing this issue as I assume you're satisfied.
